# Generated by Django 3.2.5 on 2022-02-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslmaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostnameentry',
            name='mailcount',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='hostnameentry',
            name='hostname',
            field=models.CharField(default='npci.org.in', max_length=50),
        ),
    ]
