# Generated by Django 3.2.5 on 2022-02-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslmaster', '0003_auto_20220207_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostnameentrydns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
