# Generated by Django 3.2.5 on 2022-02-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslmaster', '0004_hostnameentrydns'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostnameentrydns',
            name='mailcount',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
